export const cabecaItems = [
  "Cabeca_1", "Cabeca_2", "Cabeca_3"
];

export const faceItems = [
  "Expressao_1", "Expressao_2", "Expressao_3", "Expressao_4", "Expressao_5", "Expressao_6", "Expressao_7", "Expressao_8", "Expressao_9", "Expressao_10", "Expressao_11", "Expressao_Coracao"
];

export const acessorioItems = [
  "1_oculos_netro", "Antena", "Antena_1", "Antena_2", "Antena_3", "Antena_4", "Antena_Azul", "Antena_Lacinho_laranja", "Antena_Lacinho_roxo", "Antena_Lacinho_Verde", "Antena_Lacinho_vermelho", "Antena_Laranja", "Antena_Rosa", "Antena_Roxo", "Headset_azul", "Headset_laranja", "Headset_roxo", "Headset_Verde", "Headset_vermelho", "Mochila_Vitrine", "Oculos_Azul", "Oculos_colorido", "Oculos_escuro", "Oculos_laranja", "Oculos_Rosa", "Prancheta_1"
];

export const troncoItems = [
  "Tronco_Branco_Modelo_1_Azul", "Tronco_Branco_modelo_1_Com_Mochila_Azul", "Tronco_Branco_modelo_1_Com_Mochila_Laranja", "Tronco_Branco_modelo_1_Com_Mochila_Roxo", "Tronco_Branco_modelo_1_Com_Mochila_Tradicional", "Tronco_Branco_modelo_1_Com_Mochila_Verde", "Tronco_Branco_modelo_1_Com_Mochila_Vermelho", "Tronco_Branco_Modelo_1_Laranja", "Tronco_Branco_Modelo_1_Roxo", "Tronco_Branco_Modelo_1_Tradicional", "Tronco_Branco_Modelo_1_Verde", "Tronco_Branco_Modelo_1_Vermelho", "Tronco_Branco_modelo_2_Azul", "Tronco_Branco_modelo_2_Com_Mochila_Azul", "Tronco_Branco_modelo_2_Com_Mochila_Laranja", "Tronco_Branco_modelo_2_Com_Mochila_Roxo", "Tronco_Branco_modelo_2_Com_Mochila_Tradicional", "Tronco_Branco_modelo_2_Com_Mochila_Verde", "Tronco_Branco_modelo_2_Com_Mochila_Vermelho", "Tronco_Branco_modelo_2_Laranja", "Tronco_Branco_modelo_2_Roxo", "Tronco_Branco_modelo_2_Tradicional", "Tronco_Branco_modelo_2_Verde", "Tronco_Branco_modelo_2_Vermelho", "Tronco_Branco_modelo_3_Azul", "Tronco_Branco_modelo_3_Com_Mochila_Azul", "Tronco_Branco_modelo_3_Com_Mochila_Laranja", "Tronco_Branco_modelo_3_Com_Mochila_Roxo", "Tronco_Branco_modelo_3_Com_Mochila_Tradicional", "Tronco_Branco_modelo_3_Com_Mochila_Verde", "Tronco_Branco_modelo_3_Com_Mochila_Vermelho", "Tronco_Branco_modelo_3_Laranja", "Tronco_Branco_modelo_3_Roxo", "Tronco_Branco_modelo_3_Tradicional", "Tronco_Branco_modelo_3_Verde", "Tronco_Branco_modelo_3_Vermelho", "Tronco_Cinza_Modelo_1_Azul", "Tronco_Cinza_modelo_1_Com_Mochila_Azul", "Tronco_Cinza_modelo_1_Com_Mochila_Laranja", "Tronco_Cinza_modelo_1_Com_Mochila_Roxo", "Tronco_Cinza_modelo_1_Com_Mochila_Tradicional", "Tronco_Cinza_modelo_1_Com_Mochila_Verde", "Tronco_Cinza_modelo_1_Com_Mochila_Vermelho", "Tronco_Cinza_Modelo_1_Laranja", "Tronco_Cinza_Modelo_1_roxo", "Tronco_Cinza_Modelo_1_tradicional", "Tronco_Cinza_Modelo_1_Verde", "Tronco_Cinza_Modelo_1_Vermelho", "Tronco_Cinza_modelo_2_Azul", "Tronco_Cinza_modelo_2_Com_Mochila_Azul", "Tronco_Cinza_modelo_2_Com_Mochila_Laranja", "Tronco_Cinza_modelo_2_Com_Mochila_Roxo", "Tronco_Cinza_modelo_2_Com_Mochila_Tradicional", "Tronco_Cinza_modelo_2_Com_Mochila_Verde", "Tronco_Cinza_modelo_2_Com_Mochila_Vermelho", "Tronco_Cinza_modelo_2_Laranja", "Tronco_Cinza_modelo_2_Roxo", "Tronco_Cinza_modelo_2_Tradicional", "Tronco_Cinza_modelo_2_Verde", "Tronco_Cinza_modelo_2_Vermelho", "Tronco_Cinza_modelo_3_Azul", "Tronco_Cinza_modelo_3_Com_Mochila_Azul", "Tronco_Cinza_modelo_3_Com_Mochila_Laranja", "Tronco_Cinza_modelo_3_Com_Mochila_Roxo", "Tronco_Cinza_modelo_3_Com_Mochila_Verde", "Tronco_Cinza_modelo_3_Com_Mochila_Vermelho", "Tronco_Cinza_modelo_3_Laranja", "Tronco_Cinza_modelo_3_Roxo", "Tronco_Cinza_modelo_3_Tradicional", "Tronco_Cinza_modelo_3_Verde", "Tronco_Cinza_modelo_3_Vermelho" 
];

export const bracosItems = [
  "Bracos_1_Azul", "Bracos_1_Azul_com_espada_Verde", "Bracos_1_Azul_com_espada_Vermelho", "Bracos_1_Laranja", "Bracos_1_Laranja_com_espada_Verde", "Bracos_1_Laranja_com_espada_Vermelho", "Bracos_1_Roxo", "Bracos_1_Roxo_com_espada_Verde", "Bracos_1_Roxo_com_espada_Vermelho", "Bracos_1_tradicional", "Bracos_1_tradicional_com_espada_Verde", "Bracos_1_tradicional_com_espada_Vermelho", "Bracos_1_Verde", "Bracos_1_Verde_com_espada_Verde", "Bracos_1_Verde_com_espada_Vermelho", "Bracos_1_Vermelho", "Bracos_1_Vermelho_com_espada_Verde", "Bracos_1_Vermelho_com_espada_Vermelho", "Bracos_4_Azul", "Bracos_4_com_Espada_Verde_Azul", "Bracos_4_com_Espada_Verde_Laranja", "Bracos_4_com_Espada_Verde_Roxo", "Bracos_4_com_Espada_Verde_Tradicional", "Bracos_4_com_Espada_Verde_Verde", "Bracos_4_com_Espada_Verde_Vermelho", "Bracos_4_com_Espada_Vermelha_Azul", "Bracos_4_com_Espada_Vermelha_Laranja", "Bracos_4_com_Espada_Vermelha_Roxo", "Bracos_4_com_Espada_Vermelha_Tradicional", "Bracos_4_com_Espada_Vermelha_Verde", "Bracos_4_Laranja", "Bracos_4_Roxo", "Bracos_4_Tradicional", "Bracos_4_Verde", "Bracos_4_Vermelho", "Bracos_5_Azul", "Bracos_5_Com_espada_Verde_Azul", "Bracos_5_Com_espada_Verde_Laranja", "Bracos_5_Com_espada_Verde_Roxo", "Bracos_5_Com_espada_Verde_Verde", "Bracos_5_Com_espada_Verde_Vermelho", "Bracos_5_Com_espada_vermelha_Azul", "Bracos_5_Com_espada_vermelha_Laranja", "Bracos_5_Com_espada_vermelha_Verde", "Bracos_5_Com_espada_vermelha_Vermelho", "Bracos_5_Com_espadas_vermelha_Roxo", "Bracos_5_Laranja", "Bracos_5_Roxo", "Bracos_5_Tradicional", "Bracos_5_verde", "Bracos_5_Vermelho", "Bracos_modelo_1", "Bracos_modelo_1_1", "Bracos_modelo_1_Com_Sabre_Verde", "Bracos_modelo_1_Com_Sabre_Vermelha", "Bracos_modelo_2", "Bracos_modelo_2_com_espada_vermelha", "Bracos_modelo_2_com_espada_vermelha_2", "Bracos_4_com_Espada_Vermelha_Vermelho"
];

export const pernasItems = [
  "Flutuante_8_Azul", "Flutuante_8_Laranja", "Flutuante_8_Roxo", "Flutuante_8_Verde", "Flutuante_8_Vermelho", "Perna_Cinza_LIsa", "Pernas Branco_1_Vermelho", "Pernas_2_Azul", "Pernas_2_Laranja", "Pernas_2_LIsa", "Pernas_2_Roxo", "Pernas_2_Verde", "Pernas_2_Vermelho", "Pernas_3_lisa", "Pernas_3_Tenis_Azul", "Pernas_3_Tenis_laranja", "Pernas_3_Tenis_Roxo", "Pernas_3_Tenis_tradicional", "Pernas_3_Tenis_Verde", "Pernas_3_Tenis_Vermelho", "Pernas_4_Azul", "Pernas_4_Laranja", "Pernas_4_Roxo", "Pernas_4_tradicional", "Pernas_4_Verde", "Pernas_4_Vermelho", "Pernas_6_Azul", "Pernas_6_Laranja", "Pernas_6_Roxo", "Pernas_6_Tradicional", "Pernas_6_Verde", "Pernas_6_Vermelho", "Pernas_7_Azul", "Pernas_7_Laranja", "Pernas_7_Lisas", "Pernas_7_Roxo", "Pernas_7_Verde", "Pernas_7_Vermelho", "Pernas_8_tenis_azul", "Pernas_8_tenis_laranja", "Pernas_8_tenis_roxo", "Pernas_8_tenis_tradicional", "Pernas_8_tenis_verde", "Pernas_8_tenis_vermelho", "Pernas_Branco_1_Azul", "Pernas_Branco_1_Laranja", "Pernas_Branco_1_Roxo", "Pernas_Branco_1_Tradicional", "Pernas_Branco_1_Verde", "Pernas_Branco_Lisa", "Pernas_Cinza_1_Azul", "Pernas_Cinza_1_Laranja", "Pernas_Cinza_1_Roxo", "Pernas_Cinza_1_Tradicional", "Pernas_Cinza_1_Verde", "Pernas_Cinza_1_Vermelho", "Roda_5_Azul", "Roda_5_Laranja", "Roda_5_Roxo", "Roda_5_Tradicional", "Roda_5_Verde", "Roda_5_Vermelho"
];

export const petItems = [
  "Robotcat", "Robotdog"
];

export const itemsDoAvatar = {
  cabeca: ["Cabeca_1", "Cabeca_2", "Cabeca_3"],
  face: ["Expressao_1", "Expressao_2", "Expressao_3", "Expressao_4"],
  acessorios: ["Antena_Lacinho_roxo", "Antena_Lacinho_Verde", "Antena_Lacinho_vermelho", "Antena_Laranja", "Antena_Rosa", "Antena_Roxo", "Headset_azul", "Headset_laranja", "Headset_roxo", "Headset_Verde", "Oculos_Azul", "Oculos_colorido", "Oculos_escuro", "Oculos_laranja"],
  tronco: ["Tronco_Branco_modelo_1_Com_Mochila_Verde", "Tronco_Branco_modelo_1_Com_Mochila_Vermelho", "Tronco_Branco_Modelo_1_Laranja", "Tronco_Branco_Modelo_1_Roxo", "Tronco_Branco_Modelo_1_Tradicional"],
  braco: ["Bracos_5_verde", "Bracos_5_Vermelho", "Bracos_modelo_1", "Bracos_modelo_1_1", "Bracos_modelo_1_Com_Sabre_Verde", "Bracos_modelo_1_Com_Sabre_Vermelha", "Bracos_modelo_2", "Bracos_modelo_2_com_espada_vermelha", "Bracos_modelo_2_com_espada_vermelha_2"],
  pernas: ["Pernas_4_Azul", "Pernas_Branco_1_Tradicional", "Pernas_Branco_1_Verde", "Pernas_Branco_Lisa", "Pernas_Cinza_1_Azul", "Pernas_Cinza_1_Laranja", "Pernas_Cinza_1_Roxo", "Pernas_Cinza_1_Tradicional", "Pernas_Cinza_1_Verde", "Pernas_Cinza_1_Vermelho", "Roda_5_Azul", "Roda_5_Laranja", "Roda_5_Roxo", "Roda_5_Tradicional", "Roda_5_Verde", "Roda_5_Vermelho"],
  pet: ["Robotcat"]
}